---
- name: Playbook to prepare DevOps desktop
  hosts: localhost
  connection: local

  vars:
    username: "joaolms"
  
  tasks:
  - name: utils
    become: true
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - chrome-gnome-shell # this package has changed to "gnome-browser-connector" in Ubuntu 23.04 and newer
        - code
        - curl
        - gh
        - git
        - gnupg
        - keepassxc
        - lsb-release
        - make
        - ncal
        - python3-pip
        - tmux
        - ubuntu-restricted-extras
        - unzip
        - vlc
        - wget
        - zip
        - zsh
      state: latest

  - name: snaps
    become: true
    community.general.snap:
      name:
        - todoist
        - pycharm-community
        - postman
        - drawio

  - name: awscli
    pip:
      name: "awscli"

  - name: tfswitch
    become: true
    shell: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
  
  - name: tgswitch
    become: true
    shell: curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash

  - name: Add tgswitch and tfswitch to the user PATH variable
    lineinfile:
      path: /home/{{ username }}/.bashrc
      line: export PATH="$PATH:/home/{{ username }}/bin"
      state: present

  - name: code-extensions
    shell: |
      code --install-extension {{ item }}
    loop:
      - redhat.ansible
      - ms-vscode.makefile-tools
      - ms-python.python
      - vscode-icons-team.vscode-icons
      - HashiCorp.terraform
      - hashicorp.hcl
      - ms-azuretools.vscode-docker
      - ms-vscode-remote.remote-containers

# install oh-my-bash
# install steam
# install brave browser
