---
- name: Playbook to prepare DevOps desktop
  hosts: localhost
  connection: local

  vars:
    username: "joaolms"

  tasks:
    - name: Install some pre-reqs
      become: true
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - build-essential
          - ca-certificates
          - curl
          - fonts-powerline
          - gh
          - git
          - gnupg
          - pipx
          - python3-pip
          - python3-venv
          - terraform-switcher
          - tmux
          - ubuntu-restricted-extras
          - unzip
          - virtualbox
          - virtualbox-dkms
          - virtualbox-qt
          - virtualbox-guest-additions-iso
          - virtualbox-guest-utils
          - vlc
          - wget
          - zip

    - name: Check if awscli is installed
      ansible.builtin.stat:
        path: /usr/local/bin/aws
      register: awscli

    - name: Install awscli
      ansible.builtin.shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sh ./aws/install
      when: not awscli.stat.exists

    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - com.discordapp.Discord
          - org.telegram.desktop
          - md.obsidian.Obsidian
          - com.bitwarden.desktop

    - name: Check if Vagrant is installed
      ansible.builtin.stat:
        path: /usr/local/bin/vagrant
      register: vagrant

    - name: Install Vagrant
      become: true
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/vagrant/2.4.3/vagrant_2.4.3_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
      when: not vagrant.stat.exists

    - name: Check if tgswitch is installed
      ansible.builtin.stat:
        path: /usr/local/bin/tgswitch
      register: tgswitch

    - name: Install tgswitch
      become: true
      ansible.builtin.shell: |
        curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash
      when: not tgswitch.stat.exists

    - name: Install extensions to VSCode
      ansible.builtin.shell: |
        code --install-extension {{ item }}
      loop:
        - Gruntfuggly.todo-tree
        - hashicorp.terraform
        - ms-azuretools.vscode-azureterraform
        - ms-azuretools.vscode-docker
        - ms-python.python
        - ms-vscode.makefile-tools
        - ms-vscode-remote.remote-containers
        - redhat.ansible
        - vscode-icons-team.vscode-icons

# TODO: oh-my-bash
# TODO: pycharm
# TODO: todoist (appimage)
# TODO: bruno (appimage)
# TODO: vscode
# TODO: nodejs lts
# TODO: azcli (microsoft cli)
# TODO: zoom-workspace