---
- name: Playbook to prepare DevOps desktop
  hosts: localhost
  connection: local

  vars:
    username: "joaolms"

  tasks:
    - name: Install some pre-reqs
      become: true
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - build-essential
          - ca-certificates
          - curl
          - fonts-powerline
          - gh
          - git
          - gnupg
          - python3-pip
          - terraform-switcher
          - tmux
          - ubuntu-restricted-extras
          - unzip
          - vlc
          - wget
          - zip

    - name: Install awscli
      ansible.builtin.pip:
        name: "awscli"

    - name: Install tgswitch
      become: true
      ansible.builtin.shell: |
        set -o pipefail
        curl -L https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh | bash

    - name: Install extensions to VSCode
      ansible.builtin.shell: |
        code --install-extension {{ item }}
      loop:
        - Gruntfuggly.todo-tree
        - hashicorp.terraform
        - ms-azuretools.vscode-azureterraform
        - ms-azuretools.vscode-docker
        - ms-python.python
        - ms-vscode.makefile-tools
        - ms-vscode-remote.remote-containers
        - redhat.ansible
        - vscode-icons-team.vscode-icons

# TODO: oh-my-bash
# TODO: pycharm
# TODO: todoist (appimage)
# TODO: bruno (appimage)
# TODO: vscode
# TODO: nodejs lts
# TODO: azcli (microsoft cli)
