---
- name: Playbook to prepare DevOps desktop
  hosts: localhost
  connection: local

  vars:
    username: "joaolms"
    terragrunt_version: "0.36.11"
  
  tasks:
  - name: utils
    become: true
    apt:
      pkg:
        - wget
        - curl
        - zip
        - unzip
        - git
        - gh
        - tmux
        - ubuntu-restricted-extras
        - vlc
        - python3-pip
        - make
        - code
        - keepassxc
        - zsh
        - ca-certificates
        - apt-transport-https
        - lsb-release
        - gnupg
      state: latest

  - name: snaps
    become: true
    community.general.snap:
      name:
        - todoist
        - pycharm-community
        - postman
        - drawio

  - name: awscli
    pip:
      name: "awscli"

  - name: tfswitch
    become: true
    shell: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash

  - name: terragrunt
    become: true
    get_url:
      url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"
      dest: /usr/local/bin/terragrunt
      mode: 0775
      owner: "{{ username}}"
      group: "{{ username }}"

  - name: code-extensions
    shell: |
      code --install-extension {{ item }}
    loop:
      - redhat.ansible
      - ms-vscode.makefile-tools
      - ms-python.python
      - vscode-icons-team.vscode-icons
      - HashiCorp.terraform
      - hashicorp.hcl
